# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    find_tour:
        class:  AppBundle\Services\FindTour
        arguments:  ['@doctrine.orm.entity_manager']

