touristattractionimage_index:
    path:     /
    defaults: { _controller: "AppBundle:TouristAttractionImage:index" }
    methods:  GET

touristattractionimage_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:TouristAttractionImage:show" }
    methods:  GET

touristattractionimage_new:
    path:     /new
    defaults: { _controller: "AppBundle:TouristAttractionImage:new" }
    methods:  [GET, POST]

touristattractionimage_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:TouristAttractionImage:edit" }
    methods:  [GET, POST]

touristattractionimage_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:TouristAttractionImage:delete" }
    methods:  DELETE
